# Generated by Django 3.2.7 on 2021-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(blank=True, default=[], to='shop.Product', verbose_name='Товары'),
        ),
    ]
