# Generated by Django 3.2.7 on 2021-09-27 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_basket_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='Подстоимость'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Выполнен?'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговая сумма'),
        ),
        migrations.CreateModel(
            name='ProductsInBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.basket', verbose_name='Корзина')),
            ],
        ),
    ]
