# Generated by Django 3.2.7 on 2021-09-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_delete_productsinbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Не выполнен', 'Не выполнен'), ('Выполнен', 'Выполнен')], default='Не выполнен', max_length=50, verbose_name='Выполнен?'),
        ),
    ]
